# Artifact Hub repository metadata file
repositoryID: b117f922-1288-4afa-9c58-161fb3c4ac0c
owners: # (optional, used to claim repository ownership)
  - name: hansehe
    email: hans.erik.heggem@gmail.com
