apiVersion: v1
entries:
  graphql-gateway:
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2022-01-31T01:36:50.9875384+01:00"
    description: Graphql gateway helm chart for Kubernetes
    digest: 10e454ca940953331a2993e18e188566977185dd9193379f5eafb9a1f900962c
    home: https://github.com/hansehe/graphql-gateway
    icon: https://raw.githubusercontent.com/hansehe/graphql-gateway/master/helm/graphql.png
    keywords:
    - graphql
    - gateway
    - graphql-gateway
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: graphql-gateway
    sources:
    - https://github.com/hansehe/graphql-gateway
    type: application
    urls:
    - graphql-gateway-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2022-01-31T01:36:50.9865098+01:00"
    description: Graphql gateway helm chart for Kubernetes
    digest: 68284bb033e541828183dbec2da27fd5898e0f05f5b52dc9e77f64446282f684
    home: https://github.com/hansehe/graphql-gateway
    icon: https://raw.githubusercontent.com/hansehe/graphql-gateway/master/helm/graphql.png
    keywords:
    - graphql
    - gateway
    - graphql-gateway
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: graphql-gateway
    sources:
    - https://github.com/hansehe/graphql-gateway
    type: application
    urls:
    - graphql-gateway-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2022-01-31T01:36:50.9787688+01:00"
    description: Graphql gateway helm chart for Kubernetes
    digest: 1ec3c41f4bd2a4e65e0d18258ea35d272518bc4d0f26aac6c18e21a6f9e7c31f
    home: https://github.com/hansehe/graphql-gateway
    icon: https://raw.githubusercontent.com/hansehe/graphql-gateway/master/helm/graphql.png
    keywords:
    - graphql
    - gateway
    - graphql-gateway
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: graphql-gateway
    sources:
    - https://github.com/hansehe/graphql-gateway
    type: application
    urls:
    - graphql-gateway-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2022-01-31T01:36:50.9721341+01:00"
    description: Graphql gateway helm chart for Kubernetes
    digest: e2b41a89a7ce30d51d79b58eff8ae41b88434113741d355a0d2131961f0d3c38
    home: https://github.com/hansehe/graphql-gateway
    icon: https://raw.githubusercontent.com/hansehe/graphql-gateway/master/helm/graphql.png
    keywords:
    - graphql
    - gateway
    - graphql-gateway
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: graphql-gateway
    sources:
    - https://github.com/hansehe/graphql-gateway
    type: application
    urls:
    - graphql-gateway-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2022-01-31T01:36:50.9667707+01:00"
    description: Graphql gateway helm chart for Kubernetes
    digest: 5199e38338cf9d475d478219426bd5db271e4f7cea4d1d95df4a8631793ea910
    home: https://github.com/hansehe/graphql-gateway
    icon: https://raw.githubusercontent.com/hansehe/graphql-gateway/master/helm/graphql.png
    keywords:
    - graphql
    - gateway
    - graphql-gateway
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: graphql-gateway
    sources:
    - https://github.com/hansehe/graphql-gateway
    type: application
    urls:
    - graphql-gateway-0.1.0.tgz
    version: 0.1.0
generated: "2022-01-31T01:36:50.956568+01:00"
