apiVersion: v1
entries:
  graphql-gateway:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2020-10-20T11:21:50.4632955+02:00"
    description: Graphql gateway helm chart for Kubernetes
    digest: 5790d4f6d43a50d577076d497f93355106f8ccfd90787fd4536bf8bf8168e2a3
    name: graphql-gateway
    type: application
    urls:
    - graphql-gateway-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-20T11:21:50.4582943+02:00"
