version: '3.3'

services:
  graphql-gateway:
    image: hansehe/graphql-gateway:${VERSION:-latest}
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 4000:80
    environment:
      - GRAPHQL_UPDATE_GATEWAY_INTERVAL_MS=3000
      - GRAPHQL_URL_0=http://${GRAPHQL_URL_0:-service_0}/graphql
      - GRAPHQL_URL_1=http://${GRAPHQL_URL_1:-service_1}/graphql
      # Enable extra_hosts and uncomment following to do local debugging.
      # - GRAPHQL_URL_0=http://localhost-remote:5001/graphql # service_0
      # - GRAPHQL_URL_1=http://localhost-remote:5000/graphql # service_1
    extra_hosts:
      # Run ifconfig/ipconfig and look for IPv4 address starting with something like 172.*, or run DumpLocalhostIP.py.
      - "localhost-remote:${LOCALHOST_IP:-0.0.0.0}"
