version: '3.3'

services:
  graphql-gateway:
    image: hansehe/graphql-gateway:${VERSION:-latest}
    networks:
      - backend_network
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8181:80
    environment:
      - GRAPHQL_UPDATE_GATEWAY_WITH_TIMER=false
      - GRAPHQL_UPDATE_GATEWAY_WITH_MQTT=true
      - GRAPHQL_UPDATE_GATEWAY_MQTT_USERNAME=amqp
      - GRAPHQL_UPDATE_GATEWAY_MQTT_PASSWORD=amqp
      # - GRAPHQL_URL_0=http://${GRAPHQL_URL_0:-graphql-0}/graphql
      # - GRAPHQL_URL_1=http://${GRAPHQL_URL_1:-graphql-1}/graphql
      # - GRAPHQL_URL_0=http://host.docker.internal:8000/graphql
      # - GRAPHQL_URL_1=http://host.docker.internal:8001/graphql
      - GRAPHQL_URL_0=http://host.docker.internal:8002/graphql

networks:
  backend_network:
    external: true