version: '3.3'

services:
  graphql-gateway:
    image: hansehe/graphql-gateway:${VERSION:-latest}
    networks:
      - backend_network
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        - wg_public_node_url=http://localhost:8181
    ports:
      - 8181:80
    environment:
      - GRAPHQL_URL_0=http://host.docker.internal:5001/graphql
      - GRAPHQL_URL_1=http://host.docker.internal:5002/graphql

networks:
  backend_network:
    external: true