version: '3.3'

services:
  graphql-gateway:
    image: hansehe/graphql-gateway:${VERSION:-latest}
    networks:
      - backend_network
    build:
      context: ./src-legacy
      dockerfile: Dockerfile
      args:
        - wg_public_node_url=http://localhost:8181
    ports:
      - 8181:80
    environment:
      - GRAPHQL_UPDATE_GATEWAY_WITH_TIMER=false
      - GRAPHQL_UPDATE_GATEWAY_WITH_MQTT=true
      - GRAPHQL_UPDATE_GATEWAY_MQTT_USERNAME=amqp
      - GRAPHQL_UPDATE_GATEWAY_MQTT_PASSWORD=amqp
      # - GRAPHQL_URL_0=http://host.docker.internal:5001/graphql
      # - GRAPHQL_URL_1=http://host.docker.internal:5002/graphql
      # - GRAPHQL_URL_0=http://host.docker.internal:8001/graphql
      # - GRAPHQL_URL_1=http://host.docker.internal:8002/graphql
      - GRAPHQL_URL_0=http://${AUTH_PROVIDER_HOSTNAME:-host.docker.internal:5001}/graphql
      - GRAPHQL_URL_1=http://${TEMPLATE_ENGINE_HOSTNAME:-host.docker.internal:5003}/graphql
      - GRAPHQL_URL_2=http://${GENERAL_INTEGRATIONS:-host.docker.internal:5004}/graphql
      - GRAPHQL_URL_3=http://${FILE_STORE_HOSTNAME:-host.docker.internal:5007}/graphql
      - GRAPHQL_URL_4=http://${NOTIFICATION_HOSTNAME:-host.docker.internal:5012}/graphql
      - GRAPHQL_URL_5=http://${CHATBOT_HOSTNAME:-host.docker.internal:5016}/graphql
      - GRAPHQL_URL_6=http://${AIMZ_GENERAL_INTEGRATIONS_HOSTNAME:-host.docker.internal:5009}/graphql
      - GRAPHQL_URL_7=http://${AIMZ_DOCUMENT_STORE_HOSTNAME:-host.docker.internal:5000}/graphql

networks:
  backend_network:
    external: true