version: '3.3'

services:
  graphql-gateway:
    image: hansehe/graphql-gateway:${VERSION:-latest}
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8383:80
    environment:
      - GRAPHQL_UPDATE_GATEWAY_INTERVAL_MS=60000
      # - GRAPHQL_URL_0=https://service_1/graphql
      # - GRAPHQL_URL_1=https://service_2/graphql
